### PR TITLE
WIP: New Provider with Types and Docs

### PR DESCRIPTION
**Pull request by Nekototori**
Adds a new provider to handle windows firewall zones.  This allows the
ability to configure zone settings similar to GPO settings, but via
puppet.  Added documentation.

I have some very rudementary testing in place for the type and provider.

Creating this PR in the hopes to open discussion about improving integration/consistency.

I can write an example and do some basic spec testing against that if desired, but most of the spec testing for windows types and providers seem to be best done in a CI pipeline.

### CODE REVIEW

**Comment by ofalk** [comment]
@Nekototori Is this still WIP, any plans to finish it and/or rebase on the current version?

**Comment by Nekototori** [comment]
@ofalk I can rebase.  It's functioning as is, just haven't had time to add more features or integrate it tighter with the existing module for blanket functionality.

**Comment by ofalk** [comment]
@Nekototori OK, then please rebase it and make sure there are no failing tests and then I can have a more detailed look. OK?

**Comment by ofalk** [comment]
@alexjfisher Added you and me as reviewer. Your fault, you commented on this PR :stuck_out_tongue:

**Comment by Nekototori** [comment]
@ofalk I've got it rebased and passing tests.  Sorry it took me a bit to get to this part.

**Comment by alexjfisher** [comment]
@Nekototori This doesn't look like it's been rebased.  There are 36 commits now in this PR.

**Comment by Nekototori** [comment]
Ah, did you want everything squashed?  I just did a git rebase with the master branch here.

**Comment by alexjfisher** [comment]
@Nekototori I wasn't *necessarily* expecting just a single commit, but after a successful rebase, I wouldn't expect to see all those merge commits and multiple commits with the same commit messages etc.

**Comment by alexjfisher** [comment]
@Nekototori You may have got into trouble because you made all your changes on your fork's master branch instead of a separate topic branch.  Best practice is for your master to only contain commits that are present on upstream/master.  This way whenever you merge upstream/master onto master, you should always end up with a fast-forward merge and your master will remain a perfect copy.  See https://help.github.com/en/articles/syncing-a-fork

**Comment by ofalk** [comment]
Oh. I've been to slow with getting back to this here. Thanks for taking care @alexjfisher .
Thanks for your work @Nekototori !

**Pull request closed without merging**
